### ISSUE TITLE
Binder: fails to build ipycytoscape

### ISSUE THREAD

**Issue by pwrose** [covid-19-net/covid-19-community#344]
Failed to build ipycytoscape
Pip subprocess error:
  Running command git clone -q https://github.com/pwrose/ipycytoscape.git /tmp/pip-req-build-_8vpzekr
  ERROR: Command errored out with exit status 1:
   command: /srv/conda/envs/notebook/bin/python /srv/conda/envs/notebook/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpdkkmg4qe
       cwd: /tmp/pip-req-build-_8vpzekr
  Complete output (122 lines):
  running bdist_wheel
  running jsdeps
  Installing build dependencies with npm.  This may take a while...
  > npm install

  added 1246 packages, and audited 1313 packages in 44s

  21 vulnerabilities (13 low, 5 moderate, 3 high)

  To address issues that do not require attention, run:
    npm audit fix

  To address all issues (including breaking changes), run:
    npm audit fix --force

  Run `npm audit` for details.
  npm notice
  npm notice New minor version of npm available! 7.0.8 -> 7.11.0
  npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.11.0>
  npm notice Run `npm install -g npm@7.11.0` to update!
  npm notice
  > npm run build

  > jupyter-cytoscape@1.2.0 build
  > npm run build:lib && npm run build:all

  > jupyter-cytoscape@1.2.0 build:lib
  > tsc

  > jupyter-cytoscape@1.2.0 build:all
  > npm run build:labextension && npm run build:nbextension

  > jupyter-cytoscape@1.2.0 build:labextension
  > npm run clean:labextension && jupyter labextension build .

  > jupyter-cytoscape@1.2.0 clean:labextension
  > rimraf ipycytoscape/labextension

  Traceback (most recent call last):
    File "/tmp/pip-build-env-lgjks042/overlay/bin/jupyter-labextension", line 5, in <module>
      from jupyterlab.labextensions import main
    File "/tmp/pip-build-env-lgjks042/overlay/lib/python3.7/site-packages/jupyterlab/__init__.py", line 7, in <module>
      from .labapp import LabApp
    File "/tmp/pip-build-env-lgjks042/overlay/lib/python3.7/site-packages/jupyterlab/labapp.py", line 14, in <module>
      from jupyter_server._version import version_info as jpserver_version_info
    File "/tmp/pip-build-env-lgjks042/overlay/lib/python3.7/site-packages/jupyter_server/__init__.py", line 15, in <module>
      from ._version import version_info, __version__
    File "/tmp/pip-build-env-lgjks042/overlay/lib/python3.7/site-packages/jupyter_server/_version.py", line 5, in <module>
      from jupyter_packaging import get_version_info
  ImportError: cannot import name 'get_version_info' from 'jupyter_packaging' (/tmp/pip-build-env-lgjks042/overlay/lib/python3.7/site-packages/jupyter_packaging/__init__.py)
  npm ERR! code 1
  npm ERR! path /tmp/pip-req-build-_8vpzekr
  npm ERR! command failed
  npm ERR! command sh -c npm run clean:labextension && jupyter labextension build .

  npm ERR! A complete log of this run can be found in:
  npm ERR!     /home/jovyan/.npm/_logs/2021-04-23T07_57_47_862Z-debug.log
  npm ERR! code 1
  npm ERR! path /tmp/pip-req-build-_8vpzekr
  npm ERR! command failed
  npm ERR! command sh -c npm run build:labextension && npm run build:nbextension

  npm ERR! A complete log of this run can be found in:
  npm ERR!     /home/jovyan/.npm/_logs/2021-04-23T07_57_47_889Z-debug.log
  npm notice
  npm notice New minor version of npm available! 7.0.8 -> 7.11.0
  npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.11.0>
  npm notice Run `npm install -g npm@7.11.0` to update!
  npm notice
  npm ERR! code 1
  npm ERR! path /tmp/pip-req-build-_8vpzekr
  npm ERR! command failed
  npm ERR! command sh -c npm run build:lib && npm run build:all

  npm ERR! A complete log of this run can be found in:
  npm ERR!     /home/jovyan/.npm/_logs/2021-04-23T07_57_47_919Z-debug.log
  /tmp/pip-build-env-lgjks042/overlay/lib/python3.7/site-packages/setuptools/dist.py:645: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
    % (opt, underscore_opt))
  Traceback (most recent call last):
    File "/srv/conda/envs/notebook/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/srv/conda/envs/notebook/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/srv/conda/envs/notebook/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 205, in build_wheel
      metadata_directory)
    File "/tmp/pip-build-env-lgjks042/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 222, in build_wheel
      wheel_directory, config_settings)
    File "/tmp/pip-build-env-lgjks042/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 207, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-lgjks042/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 123, in <module>
      setup(**setup_args)
    File "/tmp/pip-build-env-lgjks042/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/srv/conda/envs/notebook/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/srv/conda/envs/notebook/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/srv/conda/envs/notebook/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-lgjks042/overlay/lib/python3.7/site-packages/jupyter_packaging/setupbase.py", line 503, in run
      [self.run_command(cmd) for cmd in cmds]
    File "/tmp/pip-build-env-lgjks042/overlay/lib/python3.7/site-packages/jupyter_packaging/setupbase.py", line 503, in <listcomp>
      [self.run_command(cmd) for cmd in cmds]
    File "/srv/conda/envs/notebook/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/srv/conda/envs/notebook/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-lgjks042/overlay/lib/python3.7/site-packages/jupyter_packaging/setupbase.py", line 274, in run
      c.run()
    File "/tmp/pip-build-env-lgjks042/overlay/lib/python3.7/site-packages/jupyter_packaging/setupbase.py", line 381, in run
      run(npm_cmd + ['run', build_cmd], cwd=node_package)
    File "/tmp/pip-build-env-lgjks042/overlay/lib/python3.7/site-packages/jupyter_packaging/setupbase.py", line 225, in run
      return subprocess.check_call(cmd, **kwargs)
    File "/srv/conda/envs/notebook/lib/python3.7/subprocess.py", line 363, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/srv/conda/envs/notebook/bin/npm', 'run', 'build']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for ipycytoscape
ERROR: Could not build wheels for ipycytoscape which use PEP 517 and cannot be installed directly

CondaEnvException: Pip failed

4.0  pyhd8ed1ab_0         conda-forge/noarch        36 KB
  libgcc-ng              9.2.0  h24d8f2e_2           installed
  libgcc-ng              9.3.0  h2828fa1_19          conda-forge/linux-64       8 MB
  libgomp                9.2.0  h24d8f2e_2           installed
  libgomp                9.3.0  h2828fa1_19          conda-forge/linux-64     376 KB
  libstdcxx-ng           9.2.0  hdf63c60_2           installed
  libstdcxx-ng           9.3.0  h6de172a_19          conda-forge/linux-64       4 MB
  openssl               1.1.1g  h516909a_0           installed
  openssl               1.1.1k  h7f98852_0           conda-forge/linux-64       2 MB
  sqlite                3.32.3  hcee41ef_1           installed
  sqlite                3.35.5  h74cdb3f_0           conda-forge/linux-64       1 MB
  tornado                6.0.4  py37h8f50634_1       installed
  tornado                  6.1  py37h5e8e339_1       conda-forge/linux-64     646 KB

  Summary:

  Install: 177 packages
  Upgrade: 9 packages

  Total download: 544 MB

──────────────────────────────────────────────────────────────────────────────────────

time: 293.282
Removing intermediate container d26330eb3b1f
The command '/bin/sh -c TIMEFORMAT='time: %3R' bash -c 'time mamba env update -p ${NB_PYTHON_PREFIX} -f "binder/environment.yml" && time mamba clean --all -f -y && mamba list -p ${NB_PYTHON_PREFIX} '' returned a non-zero code: 1

**Comment by pwrose** [comment]
Works now with the latest version of ipycytoscape.
